using System.Collections.Generic;
using UnityEngine;

namespace BreathOfEclipse.Data
{
    /// <summary>
    /// Root of all gameplay content. Loaded from Resources/BreathOfEclipse/GameDatabase when it exists
    /// (generated by "Breath of Eclipse/Data/Export Default Content"), otherwise built in memory from
    /// <see cref="DefaultContent"/> so the game always runs.
    /// </summary>
    [CreateAssetMenu(menuName = "Breath of Eclipse/Game Database", fileName = "GameDatabase")]
    public sealed class GameDatabase : ScriptableObject
    {
        public const string ResourcePath = "BreathOfEclipse/GameDatabase";

        [Tooltip("Version of DefaultContent this database was generated from.")]
        public int contentVersion;

        public PlayerData player;
        [Tooltip("Optional imported humanoid for the player (null = procedural mannequin).")]
        public Characters.CharacterVisualProfile playerVisual;
        public WeaponData playerWeapon;
        public ComboData playerCombos;
        public List<BreathingStyleData> styles = new List<BreathingStyleData>();
        public List<EnemyData> enemies = new List<EnemyData>();
        public List<VFXData> vfxOverrides = new List<VFXData>();
        [Tooltip("Optional real audio clips by id (procedural placeholders are used for missing ids).")]
        public AudioLibraryData audioLibrary;

        public BreathingStyleData FindStyle(string styleId)
        {
            foreach (var s in styles) if (s != null && s.styleId == styleId) return s;
            return styles.Count > 0 ? styles[0] : null;
        }

        public int IndexOfStyle(BreathingStyleData style) => styles.IndexOf(style);

        public EnemyData FindEnemy(string enemyId)
        {
            foreach (var e in enemies) if (e != null && e.enemyId == enemyId) return e;
            return null;
        }

        public VFXData FindVfxOverride(string vfxId)
        {
            foreach (var v in vfxOverrides) if (v != null && v.vfxId == vfxId && v.prefab != null) return v;
            return null;
        }

        public SkillData FindSkill(string skillId)
        {
            foreach (var s in styles)
            {
                if (s == null) continue;
                for (int i = 0; i < s.TechniqueCount; i++)
                {
                    var skill = s.GetTechnique(i);
                    if (skill != null && skill.skillId == skillId) return skill;
                }
            }
            return null;
        }
    }
}
